apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: teastore-loadgen
  name: teastore-loadgen
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: teastore-loadgen
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: teastore-loadgen
    spec:
      containers:
      - image: rstarmer/teastore_loadgen
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        name: teastore-loadgen
        env:
          - name: WEB_UI
            value: "teastore-webui.teastore.svc"
          - name: LOAD_PROFILE
            value: "load_profile.csv"
          - name: REQUEST_PROFILE
            value: "teastore_buy.lua"
          - name: OUTPUT_FILE
            value: "teastore_output.txt"
          - name: THREADS
            value: "256"
        resources:
          requests:
            cpu: 125m
            memory: 0.25Gi
          limits:
            cpu: 500m
            memory: 2.5Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
