apiVersion: v1
kind: Service
metadata:
  labels:
    app: teastore
    run: teastore-auth
  name: teastore-auth
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-auth
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: teastore
    run: teastore-db
  name: teastore-db
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    run: teastore-db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: teastore
    run: teastore-image
  name: teastore-image
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-image
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: teastore
    run: teastore-persistence
  name: teastore-persistence
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-persistence
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: teastore
    run: teastore-recommender
  name: teastore-recommender
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-recommender
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: teastore
    run: teastore-registry
  name: teastore-registry
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: teastore-registry
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: teastore
    run: teastore-webui
  name: teastore-webui
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 9980
  selector:
    run: teastore-webui
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-auth
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-auth
  template:
    metadata:
      annotations: {}
      labels:
        app: teastore
        run: teastore-auth
    spec:
      containers:
      - env:
        - name: HOST_NAME
          value: teastore-auth
        - name: REGISTRY_HOST
          value: teastore-registry
        image: descartesresearch/teastore-auth
        name: teastore-auth
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-db
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-db
  template:
    metadata:
      labels:
        app: teastore
        run: teastore-db
    spec:
      containers:
      - image: descartesresearch/teastore-db
        name: teastore-db
        ports:
        - containerPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-image
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-image
  template:
    metadata:
      annotations: {}
      labels:
        app: teastore
        run: teastore-image
    spec:
      containers:
      - env:
        - name: HOST_NAME
          value: teastore-image
        - name: REGISTRY_HOST
          value: teastore-registry
        image: descartesresearch/teastore-image
        name: teastore-image
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-persistence
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-persistence
  template:
    metadata:
      annotations: {}
      labels:
        app: teastore
        run: teastore-persistence
    spec:
      containers:
      - env:
        - name: HOST_NAME
          value: teastore-persistence
        - name: REGISTRY_HOST
          value: teastore-registry
        - name: DB_HOST
          value: teastore-db
        - name: DB_PORT
          value: "3306"
        image: descartesresearch/teastore-persistence
        name: teastore-persistence
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-recommender
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-recommender
  template:
    metadata:
      annotations: {}
      labels:
        app: teastore
        run: teastore-recommender
    spec:
      containers:
      - env:
        - name: HOST_NAME
          value: teastore-recommender
        - name: REGISTRY_HOST
          value: teastore-registry
        image: descartesresearch/teastore-recommender
        name: teastore-recommender
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-registry
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-registry
  template:
    metadata:
      annotations: {}
      labels:
        app: teastore
        run: teastore-registry
    spec:
      containers:
      - image: descartesresearch/teastore-registry
        name: teastore-registry
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teastore-webui
spec:
  selector:
    matchLabels:
      app: teastore
      run: teastore-webui
  template:
    metadata:
      annotations:
        prometheus.io/path: /stats/prometheus
        prometheus.io/port: "9901"
        prometheus.io/scheme: http
        prometheus.io/scrape: "true"
        prometheus.opsani.com/path: /stats/prometheus
        prometheus.opsani.com/port: "9901"
        prometheus.opsani.com/scheme: http
        prometheus.opsani.com/scrape: "true"
      labels:
        app: teastore
        run: teastore-webui
    spec:
      containers:
      - env:
        - name: HOST_NAME
          value: teastore-webui
        - name: REGISTRY_HOST
          value: teastore-registry
        image: descartesresearch/teastore-webui
        name: teastore-webui
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 1
            memory: 1Gi
          requests:
            cpu: 1
            memory: 1Gi
      - env:
        - name: OPSANI_ENVOY_PROXY_SERVICE_PORT
          value: "9980"
        - name: OPSANI_ENVOY_PROXIED_CONTAINER_PORT
          value: "8080"
        - name: OPSANI_ENVOY_PROXY_METRICS_PORT
          value: "9901"
        image: opsani/envoy-proxy:servox-v0.9.0
        imagePullPolicy: IfNotPresent
        name: opsani-envoy
        ports:
        - containerPort: 9980
          name: opsani-proxy
          protocol: TCP
        - containerPort: 9901
          name: opsani-metrics
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
          requests:
            cpu: 125m
            memory: 128Mi
