{
 "title": "Teastore Components",
 "time": { "from": "now-90m", "to": "now" },
 "panels": [
  {
   "title": "teastore-webui - Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_xx{kubernetes_pod_name!=\"teastore-webui-tuning\",envoy_response_code_class=~\"2|3\"}[5m]))",
     "legendFormat": "total 2XX|3XX requests/s"
    },
    {
     "expr": "avg(rate(envoy_cluster_external_upstream_rq_xx{kubernetes_pod_name=\"teastore-webui-tuning\",envoy_response_code_class=~\"2|3\"}[5m]))",
     "legendFormat": "tuning 2XX|3XX requests/s"
    }
   ]
  },
  {
   "title": "teastore-webui - Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(rate(envoy_cluster_external_upstream_rq_xx{kubernetes_pod_name!=\"teastore-webui-tuning\",envoy_response_code_class=~\"4|5\"}[5m]))",
     "legendFormat": "4XX|5XX errors/s"
    },
    {
     "expr": "avg(rate(envoy_cluster_external_upstream_rq_xx{kubernetes_pod_name=\"teastore-webui-tuning\",envoy_response_code_class=~\"4|5\"}[5m]))",
     "legendFormat": "tuning 4XX|5XX errors/s"
    }
   ]
  },
  {
   "title": "teastore-webui - Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 0 },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.5,rate(envoy_cluster_upstream_rq_time_bucket{kubernetes_pod_name!=\"teastore-webui-tuning\"}[3m])))",
     "legendFormat": "transaction latency ms"
    },
    {
     "expr": "avg(histogram_quantile(0.5,rate(envoy_cluster_upstream_rq_time_bucket{kubernetes_pod_name=\"teastore-webui-tuning\"}[3m])))",
     "legendFormat": "tuning latency ms"
    }
   ]
  },
  {
   "title": "teastore-webui - Node Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "sum(envoy_cluster_membership_total{kubernetes_pod_name!=\"teastore-webui-tuning\"})",
     "legendFormat": "main  pods"
    },
    {
     "expr": "sum(envoy_cluster_membership_total{kubernetes_pod_name=\"teastore-webui-tuning\"})",
     "legendFormat": "tuning pods"
    }
   ]
  }
 ]
}