apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: teastore-loadgen
  name: teastore-loadgen
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: teastore-loadgen
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: teastore-loadgen
    spec:
      containers:
      - image: rstarmer/teastore_jmeter_loadgen
        imagePullPolicy: Always
        #imagePullPolicy: IfNotPresent
        name: teastore-loadgen
        env:
          - name: WEB_UI
            value: teastore-webui.teastore.svc
          - name: WEB_PORT
            value: "80"
          - name: NUM_USERS
            value: "10"
          - name: RAMP_USERS
            value: "1"

        resources:
          requests:
            cpu: 125m
            memory: 0.25Gi
          limits:
            cpu: 500m
            memory: 2.5Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
