---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
 - ./../envoy

patches:
- path: env.yaml
  target:
    kind: Deployment
    name: teastore-webui

resources:
  - update-env.yaml
