---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: env.yaml
  target:
    group: apps
    kind: Deployment
    name: teastore-webui
    version: v1

bases:
 - ./../envoy
